[package]
name = "confer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tonic = "0.12.3"
prost = "0.13.4"

[build-dependencies]
tonic-build = "0.12.3"

